version: "3.9"

services:
  auth-service:
    build:
      context: ./services/auth-service
    container_name: auth-service
    ports:
      - "8000:8000"
    depends_on:
      - auth-db
    env_file:
      - ./services/auth-service/.env
    networks:
      - mentalnet

  auth-db:
    image: postgres:14
    container_name: auth-db
    ports:
      - "5436:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    
    environment:
      - POSTGRES_DB=authdb
      - POSTGRES_USER=authuser
      - POSTGRES_PASSWORD=authpass
    networks:
      - mentalnet

  chatbot-service:
    build:
      context: ./services/chatbot-service
    container_name: chatbot-service
    ports:
      - "8001:8001"
    depends_on:
      - chat-db
    env_file:
      - ./services/chatbot-service/.env
    networks:
      - mentalnet

  chat-db:
    image: postgres:14
    container_name: chat-db
    ports:
      - "5435:5432"
    volumes:
      - chat-db-data:/var/lib/postgresql/data
    
    environment:
      - POSTGRES_DB=chatdb
      - POSTGRES_USER=chatuser
      - POSTGRES_PASSWORD=chatpass
    networks:
      - mentalnet

  chat-service:
    build:
      context: ./services/chat-service
    container_name: chat-service
    ports:
      - "8002:8002"
    depends_on:
      - chatbot-db
    env_file:
      - ./services/chat-service/.env
    networks:
      - mentalnet

  chatbot-db:
    image: postgres:14
    container_name: chatbot-db
    ports:
      - "5437:5432"
    volumes:
      - chatbot-db-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=chatbotdb
    - POSTGRES_USER=chatbotuser
    - POSTGRES_PASSWORD=singer22
    networks:
      - mentalnet

  # users-service:
  #   build: 
  #     context: ./services/users-service
  #   container_name: users-service
  #   ports:
  #     - "8003:8003"
  #   depends_on:
  #     - users-db
  #   env_file:
  #     - ./services/users-service/.env
  #   networks:
  #     - mentalnet

  # users-db:
  #   image: postgres:14
  #   container_name: users-db
  #   ports:
  #     - "5438:5432"
  #   volumes:
  #     - users-db-data:/var/lib/postgresql/data
  #   networks:
  #     - mentalnet

volumes:
  auth-db-data:
  chat-db-data:
  chatbot-db-data:

networks:
  mentalnet:
    driver: bridge
