services:
  authservice:
    build:
      context: ./services/auth-service
    container_name: authservice
    ports:
      - "8000:8000"
    depends_on:
      - authdb
    env_file:
      - ./services/auth-service/.env
    networks:
      - mentalnet

  authdb:
    image: postgres:14
    container_name: authdb
    ports:
      - "5436:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    
    environment:
      - POSTGRES_DB=authdb
      - POSTGRES_USER=alexis1729
      - POSTGRES_PASSWORD=Singer22jkM
    networks:
      - mentalnet

  test-service:
    build:
      context: ./services/test-service
    container_name: test-service
    ports:
      - "8001:8001"
    depends_on:
      - test-db
    env_file:
      - ./services/test-service/.env
    networks:
      - mentalnet

  test-db:
    image: postgres:14
    container_name: test-db
    ports:
      - "5435:5432"
    volumes:
      - test-db-data:/var/lib/postgresql/data
    
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
    networks:
      - mentalnet

  ia-service:
    build:
      context: ./services/ia-service
    container_name: ia-service
    ports:
      - "8002:8002"
    depends_on:
      - ia-db
    env_file:
      - ./services/ia-service/.env
    networks:
      - mentalnet

  ia-db:
    image: postgres:14
    container_name: ia-db
    ports:
      - "5437:5432"
    volumes:
      - ia-db-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=iadb
    - POSTGRES_USER=iauser
    - POSTGRES_PASSWORD=singer22
    networks:
      - mentalnet

  users-service:
    build: 
      context: ./services/users-service
    container_name: users-service
    ports:
      - "8003:8003"
    depends_on:
      - usersdb
    env_file:
      - ./services/users-service/.env
    networks:
      - mentalnet

  usersdb:
    image: postgres:14
    container_name: usersdb
    ports:
      - "5438:5432"
    volumes:
      - users-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=usersdb
      - POSTGRES_USER=alexis1729
      - POSTGRES_PASSWORD=Singer22jkM
    networks:
      - mentalnet

  course-service:
    build:
      context: ./services/course-service
    container_name: course-service
    ports:
      - "8004:8004"
    depends_on:
      - course-db
    env_file:
      - ./services/course-service/.env
    networks:
      - mentalnet

  course-db:
    image: postgres:14
    container_name: course-db
    ports:
      - "5439:5432"
    volumes:
      - course-db-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=coursedb
    - POSTGRES_USER=courseU
    - POSTGRES_PASSWORD=singer221s
    networks:
      - mentalnet

  profesional-service:
    build:
      context: ./services/profesional-service
    container_name: profesional-service
    ports:
      - "8005:8005"
    depends_on:
      - profesional-db
    env_file:
      - ./services/profesional-service/.env
    networks:
      - mentalnet

  profesional-db:
    image: postgres:14
    container_name: profesional-db
    ports:
      - "5440:5432"
    volumes:
      - profesional-db-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=profesionaldb
    - POSTGRES_USER=profesionalU
    - POSTGRES_PASSWORD=singer223s
    networks:
      - mentalnet

  chating-service:
    build:
      context: ./services/chating-service
    container_name: chating-service
    ports: 
      - "8006:8006"
    depends_on:
      - chating-db
    env_file:
      - ./services/chating-service/.env
    networks:
      - mentalnet

  chating-db:
    image: postgres:14
    container_name: chating-db
    ports:
      - "5441:5432"
    volumes:
      - chating-db-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=chatingdb
    - POSTGRES_USER=chatinguser
    - POSTGRES_PASSWORD=singe22llm
    networks:
      - mentalnet

  notification-service:
    build:
      context: ./services/notification-service
    container_name: notification-service
    ports:
      - "8007:8007"
    depends_on:
      - notification-db
    env_file:
      - ./services/notification-service/.env
    networks:
      - mentalnet
  
  notification-db:
    image: postgres:14
    container_name: notification-db
    ports:
      - "5442:5432"
    volumes:
      - notification-db-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=notificationdb
    - POSTGRES_USER=notiuser
    - POSTGRES_PASSWORD=singernoti22
    networks:
      - mentalnet

volumes:
  auth-db-data:
  users-db-data:
  ia-db-data:
  test-db-data:
  course-db-data:
  profesional-db-data:
  chating-db-data:
  notification-db-data:

networks:
  mentalnet:
    driver: bridge
