version: "3.9"

services:
  auth-service:
    build:
      context: ./services/auth-service
    container_name: auth-service
    ports:
      - "8000:8000" #los puertos de ejecucion de un servicio
    depends_on:
      - auth-db
    env_file:
      - ./services/auth-service/.env
    networks:
      - mentalnet #red local interna de microservicios

  auth-db:
    image: postgres:14
    container_name: auth-db
    ports:
      - "5436:5432" #nota: el puerto de la base de datos sigue una secuencia, para el caso de users seria 5437:5432
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - mentalnet

  chatbot-service:
    build:
      context: ./services/chatbot-service
    container_name: chatbot-service
    ports:
      - "8001:8001"
    depends_on:
      - chat-db
    env_file:
      - ./services/chatbot-service/.env
    networks:
      - mentalnet

  chat-db:
    image: postgres:14
    container_name: chat-db
    ports:
     - "5435:5432"
    volumes:
      - chat-db-data:/var/lib/postgresql/data
    networks:
      - mentalnet

  dialogflow-chatbot:
    build:
      context: services/chat-service #ruta de localizacion de un servicio
    container_name: dialogflow-chatbot #nombre del contenedor y con el cual levantaras y contruiras el servicio
    ports:
      - "8002:8002"
    volumes:
      - ./services/chat-service/app/prueba.json:/app/prueba.json
    env_file:
      - ./services/chat-service/.env
    networks:
      - mentalnet

  users-service: #aqui la implementacion del servicio

volumes:
  auth-db-data:
  chat-db-data:

networks:
  mentalnet:
    driver: bridge
